# Numpy Tutorial

In [2]:
import numpy as np

## Exercise 1:
Create a 5x2 array of zeros and set the first column to 1.

In [45]:
first = np.zeros((5,2))
first[:,0] = 1
first

array([[1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.]])

## Exercise 2:

Create a 3x3 array of ones. Then multiply every element by 5


In [46]:
second = np.ones((3,3))
second *= 5
second

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])

## Exercise 3:

Make a 4x4 array where every element is the value 7

In [47]:
third = np.full((4,4),7)

## Exercise 4:

Create a 2x2 uninitialized array. Fill it manually with

[[9,2],
[7,6]]

In [48]:
fourth = np.empty((2,2))
fourth[:] = [[9,8],
            [7,6]]
fourth

array([[9., 8.],
       [7., 6.]])

## Exercise 5:

Conver the given list into a numpy array

In [49]:
fifth_array = [[10, 20], [30, 40], [50, 60]]
fifth = np.array(fifth_array)
print(fifth)
print(type(fifth))

[[10 20]
 [30 40]
 [50 60]]
<class 'numpy.ndarray'>


## Exercise 6:

Create an array of even numbers from 10 to 30 (inclusive)

In [50]:
sixth = np.arange(10,31,2)
sixth

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

## Exercise 7:

Generate 7 equally spaced numbers from 0 to 1

In [51]:
seventh = np.linspace(0,1,7)
seventh

array([0.        , 0.16666667, 0.33333333, 0.5       , 0.66666667,
       0.83333333, 1.        ])

## Exercise 8:

Create a 3×3 array of random integers between 1 and 10

In [52]:
eigth = np.random.randint(1,11,size=(3,3))
eigth

array([[ 5,  5,  1],
       [10,  4,  9],
       [ 4,  2,  6]])

## Exercise 9

Create an array where each value follows `value = 100 * z + 10 * y + x`

In [4]:
def ninth_fucntion(z,y,x):
    return 100 * z + 10 * y + x

ninth = np.fromfunction(ninth_fucntion,(2,3,4))
ninth


array([[[  0.,   1.,   2.,   3.],
        [ 10.,  11.,  12.,  13.],
        [ 20.,  21.,  22.,  23.]],

       [[100., 101., 102., 103.],
        [110., 111., 112., 113.],
        [120., 121., 122., 123.]]])

## Exercise 10:

Given `x = np.array([-1, 0, 1, 2])` Compute and print: 

1. the square of each element
2. absolute value
3. exponential
4. cosine

In [5]:
tenth = np.array([-1,0,1,2])
for fun in (np.square,np.abs,np.exp,np.cos):
    print(fun.__name__,fun(tenth))

square [1 0 1 4]
absolute [1 0 1 2]
exp [0.36787944 1.         2.71828183 7.3890561 ]
cos [ 0.54030231  1.          0.54030231 -0.41614684]


### Exercise 11

Stack the following arrays: 
`a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
`